### ISSUE TITLE
Unable to create MVT tiles.

### ISSUE THREAD

**Issue by hasan9206** [tilezen/TileStache#165]
Hi! Hope you guys are doing well, I have been trying to serve vector tiles in MVT format using this fork of TileStache but I am not able to get it to work. I am using PostgreSQL to store my data and have been running the [Original TileStache](https://github.com/TileStache/TileStache) successfully (serving vector tiles in GeoJSON). 

TileStache shows the following error in the terminal:
![screenshot from 2016-08-03 17 42 42](https://cloud.githubusercontent.com/assets/7081695/17365954/287f08a8-59a2-11e6-94dd-029903e878da.png)

Any idea what I am doing wrong? and what I should look into to get the MVT tiles working ( I want to render the MVT tiles in [Tangram](https://github.com/tangrams/tangram) )

_P.S: I have installed all the dependencies that were listed in the setup.py and the dependencies that the original TileStache had_

**Comment by rmarianski** [comment]
Sorry for the confusion. This repo is no longer supported, and only exists here for historical reasons. We just made an update to the readme stating that; hopefully it'll avoid confusion in the future.

Can you try the instructions [here](https://github.com/tilezen/vector-datasource/wiki/Mapzen-Vector-Tile-Service) to see if you can get started?
