### ISSUE TITLE
TileStache configuration file

### ISSUE THREAD

**Issue by andreynovikov** [tilezen/TileStache#90]
Have tried to install tile server locally but could not find working tilestache.cfg that serves Mapzen tiles. Is it public?

**Comment by rmarianski** [comment]
There is a different [tileserver](https://github.com/mapzen/tileserver) that you'll want to use. There are instructions in the [vector-datasource wiki](https://github.com/mapzen/vector-datasource/wiki/Mapzen-Vector-Tile-Service).

**Comment by andreynovikov** [comment]
@rmarianski Oh, thanks a lot!
